### PR TITLE
Allow setting a different listening address

### PR DESCRIPTION
**Pull request by fredvd**
& allow virtualenv in the buildout, set .gitignore

### CODE REVIEW

**Comment by jone** [comment]
Nice, thanks!

**Comment by jone** [comment]
I've released `ftw.maintenanceserver = 1.1.0` with this change :wink:

**Comment by fredvd** [comment]
@jone There are some more fixes coming up, see the fork/branches on zestsoftware. I'lll create more pulls thenwhen they're ready.

I noticed some strange performancd problems when running the SocketServer in production with concurrent requests that don't seem to happen locally on our development laptops. Did some googling: one improvement could be adding the SocketServer.ThreadedMixIn, another is disabling address lookup and logging on the RequestHandler in server.py

**Comment by jone** [comment]
Sure, sounds good :+1: 
Looking forward to it :wink:

**Pull request merged**
